exports.downloader = require('./downloader')
exports.stalker = require('./stalker')
exports.meme = require('./meme')
exports.fun = require('./fun')
exports.spammer = require('./spammer')
exports.education = require('./education')
